etcd:
  endpoints:
    - 10.150.30.17:2379
    - 10.150.30.18:2379
    - 10.150.30.19:2379
  baseKeyToUse: /nate/CalcBandwidth
  timeout:        5
  certpath:       E:\Documents\_Nate\Computer Related\Private keys\Etcd Certs